version: '3.8'

services:
  backend:
    build: ./backend  
    volumes:
      - ./backend:/app  
      - ./database:/app/database 
    environment:
      - DATABASE_URL=sqlite:///app/database/database.db 
    ports:
      - "8001:8001" 
  frontend:
    build: ./frontend 
    volumes:
      - ./frontend:/app  

volumes:
  db_data: 
