# Generated by Django 5.0 on 2024-01-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('trim', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('vehicle_id', models.CharField(max_length=255)),
            ],
        ),
    ]
