# Generated by Django 5.0 on 2024-01-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_ratings_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('trim', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='CarRating',
        ),
    ]
