# Generated by Django 5.0 on 2024-01-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_ratings_app', '0002_car_delete_carrating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'managed': False},
        ),
    ]
