# Generated by Django 5.0 on 2024-01-19 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_ratings_app', '0003_alter_car_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table='vehicles',
        ),
    ]
